project:
  type: book
  output-dir: docs

# Quarto options for books
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Old Masters Gallery Dresden"
  author: "Jana Cornelius"
  date: "2023-04-28"
  # this section determines which files will be added to the book as chapters
  chapters:
    - index.qmd
    - colophon.ipynb
    - collection003.qmd
    #- paintings.ipynb
    - paintings_1jc.ipynb
   # - collection_1_cornelius.ipynb
    # - video.ipynb
  repo-url: https://github.com/Janacnl/catalogue-003
  repo-actions: [edit]
  downloads: [pdf,docx,epub]
  cover-image: coverimage.png

# Quarto allows commenting using either Hypothesis or Utterances
# https://quarto.org/docs/reference/projects/books.html#comments
comments:
  hypothesis: true

format:
  # options for HTML output
  # https://quarto.org/docs/reference/formats/html.html
  html:
    number-sections: false
    # Quarto allows a number of pre-packaged themes for the HTML version
    # You can choose between them using the documentation at https://quarto.org/docs/output-formats/html-themes.html
    theme: cyborg
  # options for PDF output 
  # https://quarto.org/docs/reference/formats/pdf.html
  pdf:
    documentclass: book
  docx: 
    toc: true
  epub: 
    toc: true   
